#!/usr/bin/env node

/**
 * sync-version.mjs — Centralized version synchronization
 *
 * Reads the single source of truth (version.json) and propagates the version
 * to every consumer in the project:
 *
 *   Cargo.toml                  → [workspace.package].version
 *   package.json                → .version
 *   src-tauri/tauri.conf.json   → .version
 *   src/version.ts              → generated const export (frontend import)
 *
 * Usage:
 *   node scripts/sync-version.mjs
 *   npm run sync-version
 *
 * Invoked automatically as a `predev` / `prebuild` npm hook so the version is
 * always in sync before the frontend is compiled.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// ── Read the single source of truth ──────────────────────────────────────
const versionJsonPath = join(ROOT, 'version.json');
let versionJson;
try {
  versionJson = JSON.parse(readFileSync(versionJsonPath, 'utf-8'));
} catch (e) {
  console.error(`[sync-version] ERROR: cannot read ${versionJsonPath}:`, e.message);
  process.exit(1);
}
const VERSION = versionJson.version;
if (!VERSION || typeof VERSION !== 'string') {
  console.error('[sync-version] ERROR: version.json must contain { "version": "x.y.z" }');
  process.exit(1);
}

console.log(`[sync-version] version = ${VERSION}`);

// ── Helpers ──────────────────────────────────────────────────────────────
function readJson(filePath) {
  return JSON.parse(readFileSync(filePath, 'utf-8'));
}
function writeJson(filePath, obj) {
  writeFileSync(filePath, JSON.stringify(obj, null, 2) + '\n', 'utf-8');
}

let changedCount = 0;

// ── 1. package.json ──────────────────────────────────────────────────────
{
  const p = join(ROOT, 'package.json');
  const json = readJson(p);
  if (json.version !== VERSION) {
    json.version = VERSION;
    writeJson(p, json);
    changedCount++;
    console.log(`  [ok] package.json → ${VERSION}`);
  } else {
    console.log(`  [skip] package.json already ${VERSION}`);
  }
}

// ── 2. Cargo.toml (workspace) ─────────────────────────────────────────────
{
  const p = join(ROOT, 'Cargo.toml');
  let toml = readFileSync(p, 'utf-8');
  // Match `version = "..."` under [workspace.package]
  const re = /^(\[workspace\.package\][\s\S]*?^version\s*=\s*)"[^"]*"/m;
  const replacement = `$1"${VERSION}"`;
  if (!re.test(toml)) {
    console.error('[sync-version] ERROR: cannot find [workspace.package].version in Cargo.toml');
    process.exit(1);
  }
  const newToml = toml.replace(re, replacement);
  if (newToml !== toml) {
    writeFileSync(p, newToml, 'utf-8');
    changedCount++;
    console.log(`  [ok] Cargo.toml [workspace.package] → ${VERSION}`);
  } else {
    console.log(`  [skip] Cargo.toml already ${VERSION}`);
  }
}

// ── 3. tauri.conf.json ────────────────────────────────────────────────────
{
  const p = join(ROOT, 'src-tauri', 'tauri.conf.json');
  const json = readJson(p);
  if (json.version !== VERSION) {
    json.version = VERSION;
    writeJson(p, json);
    changedCount++;
    console.log(`  [ok] tauri.conf.json → ${VERSION}`);
  } else {
    console.log(`  [skip] tauri.conf.json already ${VERSION}`);
  }
}

// ── 4. src/version.ts (generated, for frontend import) ───────────────────
{
  const p = join(ROOT, 'src', 'version.ts');
  const content = [
    '// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.',
    '// Single source of truth: version.json in the repository root.',
    `export const APP_VERSION = "${VERSION}";`,
    '',
  ].join('\n');
  const existing = (() => { try { return readFileSync(p, 'utf-8'); } catch { return ''; } })();
  if (existing !== content) {
    writeFileSync(p, content, 'utf-8');
    changedCount++;
    console.log(`  [ok] src/version.ts generated (APP_VERSION = "${VERSION}")`);
  } else {
    console.log(`  [skip] src/version.ts up-to-date`);
  }
}

// ── Summary ───────────────────────────────────────────────────────────────
if (changedCount > 0) {
  console.log(`[sync-version] ${changedCount} file(s) updated.`);
} else {
  console.log('[sync-version] all files already in sync.');
}
